import { ApiProperty } from '@nestjs/swagger';

export class PasswordResetResponseDto {
  @ApiProperty({
    description:
      'Password reset link generated by Firebase. Send this to the user so they can set their password.',
    example: 'https://accounts.google.com/...',
  })
  resetLink: string;
}
